#!/usr/bin/env bash
# a script that sets up firewall through ufw

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow ssh

sudo ufw enable

sudo ufw allow https
sudo ufw allow http
